platform :ios, '7.0'
pod 'Masonry', '~> 0.6.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.2'
pod 'AFNetworking', '~> 2.6.1'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.9'
pod 'CYLTabBarController' ,'~>1.2.1'
pod 'ReactiveCocoa', '~>  2.5'